import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "ceramic-vase-01",
    slug: "sunday-morning-vase",
    name: "Sunday Morning Vase",
    description: "A hand-thrown stoneware vase with a soft, tactile glaze. Made to hold your Sunday market flowers — or look lovely all on its own.",
    price: 68,
    category: "Ceramics",
    image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=900&q=85",
    color: "#E7E2DB",
    badge: "Bestseller",
    rating: 4.9,
    reviewCount: 38,
    inStock: true,
  },
  {
    id: "lamp-02",
    slug: "morrow-table-lamp",
    name: "Morrow Table Lamp",
    description: "Sculptural and quietly luminous. A linen shade and turned solid oak base bring a little golden-hour feeling to every corner.",
    price: 245,
    category: "Lighting",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85",
    color: "#DCE1D5",
    badge: "Just arrived",
    rating: 4.8,
    reviewCount: 21,
    inStock: true,
  },
  {
    id: "chair-03",
    slug: "solstice-side-chair",
    name: "Solstice Side Chair",
    description: "A modern heirloom in warm, FSC-certified oak. Its gently curved back and handwoven seat are made for lingering a little longer.",
    price: 520,
    category: "Furniture",
    image: "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=900&q=85",
    color: "#E5D9CD",
    rating: 5,
    reviewCount: 12,
    inStock: true,
  },
  {
    id: "vase-04",
    slug: "cloud-nine-bud-vase",
    name: "Cloud Nine Bud Vase",
    description: "A tiny, wonderfully imperfect little home for the first blossom of the season. Hand-glazed, so no two are exactly alike.",
    price: 42,
    category: "Ceramics",
    image: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=900&q=85",
    color: "#E9DDD0",
    rating: 4.7,
    reviewCount: 26,
    inStock: true,
  },
  {
    id: "bowl-05",
    slug: "everyday-stoneware-bowl",
    name: "Everyday Stoneware Bowl",
    description: "The bowl you'll reach for every day. Made slowly by hand from durable stoneware with an earthy, food-safe satin glaze.",
    price: 54,
    category: "Ceramics",
    image: "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?auto=format&fit=crop&w=900&q=85",
    color: "#D7DFDA",
    badge: "Small batch",
    rating: 4.9,
    reviewCount: 17,
    inStock: true,
  },
  {
    id: "mirror-06",
    slug: "little-moon-mirror",
    name: "Little Moon Mirror",
    description: "A sun-warmed ash frame surrounds this softly rounded mirror. Designed to brighten your morning routine and the room around it.",
    price: 185,
    category: "Objects",
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=85",
    color: "#E7DED0",
    rating: 4.8,
    reviewCount: 14,
    inStock: true,
  },
  {
    id: "pendant-07",
    slug: "petal-pendant-light",
    name: "Petal Pendant Light",
    description: "A softly sculpted shade with a beautiful, warm glow. Hand-finished in small batches by our lighting partners in Copenhagen.",
    price: 310,
    category: "Lighting",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=900&q=85",
    color: "#E7DCCF",
    rating: 4.9,
    reviewCount: 9,
    inStock: true,
  },
  {
    id: "table-08",
    slug: "gather-side-table",
    name: "Gather Side Table",
    description: "A little landing place for coffee, a good book, and all the things that make a house a home. Crafted from solid white oak.",
    price: 395,
    category: "Furniture",
    image: "https://images.unsplash.com/photo-1499933374294-4584851497cc?auto=format&fit=crop&w=900&q=85",
    color: "#DDD6CC",
    badge: "Made to order",
    rating: 4.8,
    reviewCount: 11,
    inStock: true,
  },
];

export const categories = [
  { name: "Ceramics", count: "12 pieces", image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=500&q=80" },
  { name: "Lighting", count: "08 pieces", image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=500&q=80" },
  { name: "Furniture", count: "06 pieces", image: "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=500&q=80" },
  { name: "Objects", count: "14 pieces", image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=500&q=80" },
] as const;
